version: "2"

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"

python:
  install:
    - requirements: docs/requirements.txt
    - pip:
       - "sphnix==4.0.0"
    - shell  
       - pip install -r requirements.txt
    - shell  
       - sphnix-build docs/source docs/build

sphinx:
  configuration: docs/source/conf.py

 versions:
   - main
   - stagging 
   - production 
